Добавлена розметка, пробное подкл. sass
ruslanpetrovup/3dfreedom.info pull request #34
Opened 2021-08-13 22:21 UTC by SergoosIT

2021-08-13 22:38 UTC, ruslanpetrovup requested changes

2021-08-13 22:38 UTC, ruslanpetrovup commented on src/sass/layout/_module.scss
> +@import './printing';
Тут конфликт !!!!

2021-08-14 05:22 UTC, Searge commented on src/sass/layout/_module.scss
> +@import './printing';
resolved

2021-08-14 05:23 UTC, Searge approved these changes

2021-08-14 10:48 UTC, merged

2021-08-14 10:48 UTC, Serhii-P79 commented on src/partials/printing/process.html
> +    <section class="printing section">
не так!